# Generated by Django 4.2.2 on 2023-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexCaruselActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Carusel Title')),
                ('name', models.CharField(max_length=60, verbose_name='Carusel name')),
                ('abaut', models.TextField(verbose_name='Carusel abaut')),
                ('button_name', models.CharField(max_length=30, verbose_name='Carusel button name')),
                ('img', models.ImageField(upload_to='index_images', verbose_name='Carusel image')),
                ('logo', models.ImageField(upload_to='index_images', verbose_name='Carusel logo')),
            ],
        ),
        migrations.DeleteModel(
            name='FEATURES_ITEMS',
        ),
    ]
