# Generated by Django 4.2.2 on 2023-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_category_product_brand_categoryegory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Product img'),
        ),
    ]
